### ISSUE TITLE
TideLift link in readme.md is broken

### ISSUE THREAD

**Issue by JasonRShaver** [NServiceBusExtensions/Newtonsoft.Json.Encryption#290]
Results in a 404:

Support is available via a [Tidelift Subscription](https://tidelift.com/subscription/pkg/nuget-nservicebus.json.encryption?utm_source=nuget-nservicebus.json.encryption&utm_medium=referral&utm_campaign=enterprise).

**Comment by SimonCropp** [comment]
should be fixed now
